###################################################
# 《YiiPlus脚手架》持续集成配置
#
# YiiPlus Scaffold
# Application  [common console admin app pc h5]
# Environments [Development Testing Production]
###################################################
# 任务路线图
# 
# Development
#   build:composer
#   codeview:phpcs
#   codeview:phpmd
#   codeview:codequality
#   test:unit
#   test:api
#
# Testing
#   build:composer
#   test:unit
#   test:api
#   package:test
#   deploy:test
#
# Release
#   test:unit
#   test:api
#   package:prod
#   deploy:release
#
# Production
#   test:unit
#   test:api
#   package:prod
#   deploy:prod
###################################################

image: gengxiankun/build:latest

stages:
  - build
  - test
  - package
  - deploy
  - release

before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh    
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.services:
  services:
    - name: mysql:5.6
      alias: mysql
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-storage-engine=INNODB','--innodb_large_prefix=1','--innodb_file_format=Barracuda']
    - name: redis:alpine
      alias: redis
  variables:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: yiiplus
    MYSQL_USER: web
    MYSQL_PASSWORD: web
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor

############## build ##############
build:composer:
  stage: build
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - vendor
  script:
    - composer install --prefer-dist --optimize-autoloader -n --no-interaction  --no-suggest -vvv
    - composer dump-autoload --optimize

############## test ##############
codeview:phpcs:
  stage: test
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
  script:
    - if [ ! -d "vendor" ]; then
    - composer install --prefer-dist --optimize-autoloader -n --no-interaction  --no-suggest -vvv
    - composer dump-autoload --optimize
    - fi
    - php vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=docs/,docker/,vendor/,console/migrations/,tests -w -n --colors ./
  except:
    - docs
    - develop
    - master
    - tags

codeview:phpmd:
  stage: test
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
  script:
    - if [ ! -d "vendor" ]; then
    - composer install --prefer-dist --optimize-autoloader -n --no-interaction  --no-suggest -vvv
    - composer dump-autoload --optimize
    - fi
    - vendor/bin/phpmd admin,app,common,console,pc,h5 text phpmd.xml --exclude vendor/,console/migrations --suffixes php
  except:
    - docs
    - develop
    - master
    - tags

codeview:codequality:
  stage: test
  image: docker:latest
  before_script: []
  dependencies: []
  cache: {}
  script:
    - docker pull codeclimate/codeclimate
    - VOLUME_PATH=/tmp/builds"$(echo $PWD | sed 's|^/[^/]*||')"
    - docker run --env CODECLIMATE_CODE="$VOLUME_PATH" -v /tmp/cc:/tmp/cc -v $VOLUME_PATH:/code -v /var/run/docker.sock:/var/run/docker.sock codeclimate/codeclimate analyze -f text
  except:
    - docs
    - tags
    - develop
    - master
  allow_failure: true
  when: manual

test:unit:
  stage: test
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
  extends: .services
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    - echo '跳过...'
  # script:
  #   - if [ ! -d "vendor" ]; then
  #   - composer install --prefer-dist --optimize-autoloader -n --no-interaction  --no-suggest -vvv
  #   - composer dump-autoload --optimize
  #   - fi
  #   - php init --env=Development --overwrite=y
  #   - ./yii migrate/up --interactive=0
  #   - ./vendor/bin/codecept run unit -c tests --coverage --no-colors
  # artifacts:
  #   name: "debug"
  #   when: on_failure
  #   untracked: true
  #   paths:
  #       - $CI_PROJECT_DIR/tests/_output
test:api:
  stage: test
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
  extends: .services
  script:
    - echo '跳过...'
  # script:
  #   - if [ ! -d "vendor" ]; then
  #   - composer install --prefer-dist --optimize-autoloader -n --no-interaction  --no-suggest -vvv
  #   - composer dump-autoload --optimize
  #   - fi
  #   - php init --env=Development --overwrite=y
  #   - ./yii migrate/up --interactive=0
  #   - php -S localhost:80 --docroot app/tests &>/dev/null&
  #   - ./vendor/bin/codecept run app -c tests
  # artifacts:
  #   name: "debug"
  #   when: on_failure
  #   untracked: true
  #   paths:
  #     - $CI_PROJECT_DIR/app/runtime
  #     - $CI_PROJECT_DIR/tests/_output

############## package ##############
package:develop:
  stage: package
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
  script:
    - if [ ! -d "vendor" ]; then
    - composer install --prefer-dist --optimize-autoloader -n --no-interaction  --no-suggest -vvv
    - composer dump-autoload --optimize
    - fi
    - ./pc/fis3/build.sh
    - ./h5/fis3/build.sh
    - php init --env=Testing --overwrite=y
    - rm -rf console/runtime
    - rm -rf admin/web/assets/* admin/runtime admin/tests
    - rm -rf app/web/assets/* app/runtime app/tests
    - rm -rf pc/web/assets/* pc/runtime pc/tests
    - rm -rf h5/web/assets/* h5/runtime h5/tests
    - rm -rf pc/fis3 h5/fis3
  artifacts:
    name: "$CI_PROJECT_NAME"
    untracked: false
    paths:
      - docker
      - vendor
      - common
      - console
      - admin
      - app
      - pc
      - h5
      - yii
      - docker-compose.yaml
  except:
    - docs
  only:
    - develop

package:master:
  stage: package
  before_script: []
  dependencies: []
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - vendor
  script:
    - composer install --prefer-dist --optimize-autoloader -n --no-interaction --no-suggest --no-dev -vvv
    - composer dump-autoload --optimize
    - ./pc/fis3/build.sh
    - ./h5/fis3/build.sh
    - php init --env=Production --overwrite=y
    - rm -rf console/runtime
    - rm -rf admin/web/assets/* admin/runtime admin/tests
    - rm -rf app/web/assets/* app/runtime app/tests
    - rm -rf pc/web/assets/* pc/runtime pc/tests
    - rm -rf h5/web/assets/* h5/runtime h5/tests
    - rm -rf pc/fis3 h5/fis3
  artifacts:
    name: "$CI_PROJECT_NAME"
    untracked: false
    paths:
      - docker
      - vendor
      - common
      - console
      - admin
      - app
      - pc
      - h5
      - yii
      - docker-compose.yaml
  except:
    - docs
  only:
    - master
    - tags


############## deploy ##############
deploy:test:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
    - package:develop
  script:
    - if [ ! -d "vendor" ]; then
    - exit 1
    - fi
    - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@111.230.230.147 transmission
  except:
    - docs
  only:
    - develop
  environment:
    name: test

deploy:release:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
    - package:master
  script:
    - if [ ! -d "vendor" ]; then
    - exit 1
    - fi
    - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@172.16.64.3 transmission
  except:
    - docs
  only:
    - master

deploy:prod-001:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  dependencies:
    - package:master
  script:
    - if [ ! -d "vendor" ]; then
    - exit 1
    - fi
    - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@172.16.64.10 transmission
  except:
    - docs
  only:
    - tags 

# deploy:prod-002:
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#   dependencies:
#     - package:master
#   script:
#     - if [ ! -d "vendor" ]; then
#     - exit 1
#     - fi
#     - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@192.168.2.33 transmission
#   except:
#     - docs
#   only:
#     - tags

############## release ##############
testing:
  stage: release
  variables:
    GIT_STRATEGY: none
  script:
    - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@111.230.230.147 release
  except:
    - docs
  only:
    - develop
  environment:
    name: test
release:
  stage: release
  variables:
    GIT_STRATEGY: none
  script:
    - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@172.16.64.3 release
  except:
    - docs
  only:
    - master
  environment:
    name: release
production:
  stage: release
  variables:
    GIT_STRATEGY: none
  script:
    - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@172.16.64.10 release
    # - deploy --project-name ${CI_PROJECT_NAME} --project-version $CI_COMMIT_SHA root@192.168.2.33 release
  except:
    - docs
  only:
    - tags
