version: '2'

services:
  cgi:
    container_name: cgi
    build: ./docker/files/cgi
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/www
    working_dir: /www
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
  proxy:
    container_name: proxy
    build: ./docker/files/proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/config/proxy/conf.d:/etc/nginx/conf.d
    volumes_from:
      - cgi
    working_dir: /etc/nginx
    links:
      - cgi
  crond:
    container_name: crond
    build: ./docker/files/crond
    restart: always
    volumes:
      - ./:/www
      - ./console/crontab:/etc/crontab
    working_dir: /www
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
  websocket:
    container_name: websocket
    build: ./docker/files/websocket
    restart: always
    ports:
      - "9501:9501"
    volumes_from:
      - cgi
    working_dir: /www
    command: /www/yii websocket
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.6
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/runtime/var_lib_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yiiplus
    restart: always
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/runtime/var_lib_redis:/var/lib/redis
    command: redis-server --appendonly yes
  filebeat:
    container_name: filebeat
    restart: always
    image: docker.elastic.co/beats/filebeat:6.4.3
    volumes:
      - ./docker/config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./docker/config/filebeat/prospectors.d:/usr/share/filebeat/prospectors.d
      - ./docker/config/filebeat/modules.d:/usr/share/filebeat/modules.d
    volumes_from:
      - cgi
