version: '2'

services:

    www:
        container_name: www
        build: ./docker/service/php7.1_openresty
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/www
            - ./docker/project/dev/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/project/dev/nginx.d:/etc/nginx/conf.d
            - ./docker/project/dev/php.d/50-redis.ini:/etc/php.d/50-redis.ini
        working_dir: /www
        links:
            - mysql:mysql
            - redis:redis

    fis3:
        container_name: fis3
        build: ./docker/service/fis3
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./:/www
        working_dir: /www

    mysql:
        container_name: mysql
        image: daocloud.io/library/mysql
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - ./docs/schema-mysql.sql:/schema-mysql.sql
            - ./docker/project/dev/var_lib_mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always

    redis:
        container_name: redis
        image: daocloud.io/library/redis
        restart: always
        expose:
          - "6379"
        ports:
          - "6379:6379"
        volumes:
          - ./docker/project/dev/var_lib_redis:/data
        command: redis-server --appendonly yes

    phpmyadmin:
        container_name: phpmyadmin
        image: daocloud.io/daocloud/phpmyadmin
        ports:
            - '8081:80'
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - mysql
        links:
            - mysql:mysql