version: '2'

services:
    cgi:
        container_name: cgi
        build: ./docker/dockerfiles/cgi
        restart: always
        expose:
            - "9000"
        volumes:
            - ./:/www
        working_dir: /www
        links:
            - mysql:mysql
            - redis:redis
            - fis3:fis3
            - phpmyadmin:phpmyadmin
    proxy:
        container_name: proxy
        build: ./docker/dockerfiles/proxy
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/config/proxy/conf.d:/etc/nginx/conf.d
        volumes_from:
            - cgi
        working_dir: /etc/nginx
        links:
            - cgi
    crond:
        container_name: crond
        build: ./docker/dockerfiles/crond
        restart: always
        volumes:
            - ./:/www
            - ./crontab/crontab:/etc/crontab
        working_dir: /www
        links:
            - mysql:mysql
            - redis:redis
    # queue:
    #     container_name: queue
    #     build: ./docker/dockerfiles/crond
    #     restart: always
    #     volumes:
    #         - ./:/www
    #     working_dir: /www
    #     links:
    #         - mysql:mysql
    #         - redis:redis
    #     command: ./yii queue/listen
    mysql:
        container_name: mysql
        image: daocloud.io/library/mysql:5.6
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/docker_data/var_lib_mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    redis:
        container_name: redis
        image: daocloud.io/library/redis
        restart: always
        expose:
          - "6379"
        ports:
          - "6379:6379"
        volumes:
          - ./docker/docker_data/var_lib_redis:/data
        command: redis-server --appendonly yes
    fis3:
        container_name: fis3
        build: ./docker/dockerfiles/fis3
        restart: always
        expose:
            - "8080"
        volumes:
            - ./:/www
        working_dir: /www
    phpmyadmin:
        container_name: phpmyadmin
        image: daocloud.io/daocloud/phpmyadmin
        expose:
            - '80'
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - mysql
        links:
            - mysql:mysql